import './RecipeDisplay.css'

export default function RecipeDisplay({ recipe, meal, onSave, alreadySaved, isLoggedIn, fromCache, onForceRefresh }) {
  const {
    title,
    servings,
    prepTime,
    cookTime,
    ingredients = [],
    instructions = [],
    substitutions = [],
    allergenNote,
  } = recipe

  return (
    <div className="recipe-card">
      {/* Recipe Hero */}
      <div className="recipe-hero">
        <div className="recipe-hero-content">
          <div className="recipe-tag">✓ Allergy-Friendly Recipe</div>
          <h2 className="recipe-title">{title}</h2>
          <div className="recipe-meta">
            {servings && (
              <div className="meta-item">
                <span>{servings}</span>
              </div>
            )}
            {prepTime && (
              <div className="meta-item">
                <span>Prep: {prepTime}</span>
              </div>
            )}
            {cookTime && (
              <div className="meta-item">
                <span>Cook: {cookTime}</span>
              </div>
            )}
          </div>
        </div>
      </div>

      <div className="recipe-body">
        {/* Ingredients */}
        <section className="recipe-section">
          <h3 className="section-title">
            <span className="section-icon">🛒</span>
            Ingredients
          </h3>
          <ul className="ingredients-list">
            {ingredients.map((ing, i) => (
              <li key={i} className="ingredient-item">
                <span className="ingredient-check">✓</span>
                <span className="ingredient-amount">{ing.amount}</span>
                <span className="ingredient-name">{ing.item}</span>
              </li>
            ))}
          </ul>
        </section>

        <div className="recipe-divider" />

        {/* Instructions */}
        <section className="recipe-section">
          <h3 className="section-title">
            <span className="section-icon">👨‍🍳</span>
            Instructions
          </h3>
          <ol className="instructions-list">
            {instructions.map((step, i) => (
              <li key={i} className="instruction-step">
                <div className="step-number">{i + 1}</div>
                <p className="step-text">
                  {/* Strip leading "Step N:" if Claude included it */}
                  {step.replace(/^step\s*\d+[:.]\s*/i, '')}
                </p>
              </li>
            ))}
          </ol>
        </section>

        {/* Substitutions */}
        {substitutions.length > 0 && (
          <>
            <div className="recipe-divider" />
            <section className="recipe-section">
              <h3 className="section-title">
                <span className="section-icon">🔄</span>
                Substitutions Made
              </h3>
              <div className="substitutions-grid">
                {substitutions.map((sub, i) => (
                  <div key={i} className="sub-card">
                    <div className="sub-swap">
                      <span className="sub-original">{sub.original}</span>
                      <span className="sub-arrow">→</span>
                      <span className="sub-replacement">{sub.substitute}</span>
                    </div>
                    {sub.reason && (
                      <p className="sub-reason">{sub.reason}</p>
                    )}
                  </div>
                ))}
              </div>
            </section>
          </>
        )}

        {/* Allergen Safety Note */}
        {allergenNote && (
          <div className="safety-note">
            <div className="safety-note-header">
              <span className="safety-icon">🛡️</span>
              <strong>Allergy Safety Note</strong>
            </div>
            <p>{allergenNote}</p>
          </div>
        )}

        {/* AI Disclaimer */}
        <div className="ai-disclaimer">
          <span className="ai-disclaimer-icon">⚠️</span>
          <p>Please verify all ingredients against your specific allergies before preparing this recipe. This recipe was generated by AI and may not account for all individual sensitivities or cross-contamination risks.</p>
        </div>

        {/* Actions */}
        <div className="recipe-actions">
          {onSave && (
            <button
              className={`action-btn action-save ${alreadySaved ? 'action-save--saved' : ''}`}
              onClick={onSave}
              disabled={alreadySaved}
            >
              {alreadySaved ? '✓ Saved' : isLoggedIn ? '💾 Save Recipe' : '🔒 Log In to Save'}
            </button>
          )}
          <button
            className="action-btn action-print"
            onClick={() => window.print()}
          >
            🖨️ Print Recipe
          </button>
          <button
            className="action-btn action-copy"
            onClick={() => {
              const text = formatRecipeAsText(recipe)
              navigator.clipboard.writeText(text).catch(() => {})
            }}
          >
            📋 Copy to Clipboard
          </button>
        </div>
      </div>
    </div>
  )
}

function formatRecipeAsText(recipe) {
  const lines = []
  lines.push(recipe.title)
  lines.push('='.repeat(recipe.title.length))
  if (recipe.servings) lines.push(`Servings: ${recipe.servings}`)
  if (recipe.prepTime) lines.push(`Prep: ${recipe.prepTime}`)
  if (recipe.cookTime) lines.push(`Cook: ${recipe.cookTime}`)
  lines.push('')
  lines.push('INGREDIENTS')
  lines.push('-----------')
  recipe.ingredients?.forEach(i => lines.push(`• ${i.amount} ${i.item}`))
  lines.push('')
  lines.push('INSTRUCTIONS')
  lines.push('------------')
  recipe.instructions?.forEach((s, i) => lines.push(`${i + 1}. ${s.replace(/^step\s*\d+[:.]\s*/i, '')}`))
  if (recipe.substitutions?.length > 0) {
    lines.push('')
    lines.push('SUBSTITUTIONS')
    lines.push('-------------')
    recipe.substitutions.forEach(s => lines.push(`• ${s.original} → ${s.substitute}: ${s.reason}`))
  }
  if (recipe.allergenNote) {
    lines.push('')
    lines.push('ALLERGY NOTE')
    lines.push('------------')
    lines.push(recipe.allergenNote)
  }
  lines.push('')
  lines.push('DISCLAIMER')
  lines.push('----------')
  lines.push('Please verify all ingredients against your specific allergies before preparing this recipe. This recipe was generated by AI and may not account for all individual sensitivities or cross-contamination risks.')
  return lines.join('\n')
}
